### ISSUE TITLE
Bootstrap Position の Utility APIが適応されない

### ISSUE THREAD

**Issue by furukawaeiichi** [furukawaeiichi/CREDO_QUEST#30]
- 質問内容・実現したいこと
Bootstrap 5.0.2にて、Positionを指定できるよう設定したい。
https://getbootstrap.jp/docs/5.0/utilities/position/

- 現状発生している問題
デフォルトで設定されている「0, 50, 100」の数値は表示できる。

だが、その間の数値（10-40, 60-90）は「Utility API」を用いて設定しなければいけない認識です。
しかし、その設定を記述したコードが、ビューに適応されません。
https://getbootstrap.jp/docs/5.0/utilities/api/#using-the-api

- どの処理までうまく動いているのか
デフォルト「0, 50, 100」の表示。

top, start 10-40, 60-90は、top, start-0の上に重なって表示されてしまいます。

<img width="1280" alt="スクリーンショット 2023-06-10 18 27 07" src="https://github.com/furukawaeiichi/CREDO_QUEST/assets/102509805/6b73d9a0-beda-40b9-a5cc-bd1005cb2469">

- 該当のソースコード

app/views/users/index.html.erb
`
< div class ="position-relative">
  < div class = "position-absolute top-0 start-0">top-0 start-0</div>
  < div class = "position-absolute top-10 start-10">top-10 start-10</div>
  < div class="position-absolute top-20 start-20">top-20 start-20</div>
  < div class="position-absolute top-30 start-30">top-30 start-30</div>
  < div class="position-absolute top-40 start-40">top-40 start-40</div>
  < div class="position-absolute top-50 start-50">top-50 start-50</div>
  < div class="position-absolute top-60 start-60">top-60 start-60</div>
  < div class="position-absolute top-70 start-70">top-70 start-70</div>
  < div class="position-absolute top-80 start-80">top-80 start-80</div>
  < div class="position-absolute top-90 start-90">top-90 start-90</div>
  < div class="position-absolute top-100 start-100">top-100 start-100</div>
< /div>
`

app/assets/stylesheets/_utilities.scss
`
$utilities: (
  "opacity": (
    property: opacity,
    values: (
      0: 0,
      10: .1,
      20: .2,
      30: .3,
      40: .4,
      50: .5,
      60: .6,
      70: .7,
      80: .8,
      90: .9,
      100: 1,
    )
  )
 );
`

- エラーから考えられる原因
エラー文は表示されませんでした。

- 試したこと
ドキュメントを参考に何通りか、app/assets/stylesheets/_utilities.scssのコード記述を試しました。

ご助言いただけたら幸いです。

**Comment by furukawaeiichi** [comment]
こちら該当の開発ブランチです。
https://github.com/furukawaeiichi/CREDO_QUEST/commit/9f2f3730a58e0c31b584dd6559f594e7afac1347

**Comment by furukawaeiichi** [comment]
BootstrapをCDNでインストールしていたため、gemをインストールしてPositionの指定ができないか試しております。

現在の作業進捗は、まだPositionの指定ができず、CDNでBootstrapが適応されていたデザインが崩れてしまった状態です。

**Comment by Tsuchiya2** [comment]
具体的にはどんなことがしたいのかが、ちゃんと把握できていないため、期待している回答とは異なるかもしれませんが。。。

- それ用のcssを書いて適応すれば良いのではと思いました。（Bootstrapをオーバーライドする方法ではなく、別途それ用のcssを用意して適応させる感じです）

---

それとは別にいただいたIssueの内容をChatGPTに投げた際の解答例を以下に共有しておきます。

まず、BootstrapのユーティリティAPIを使用するためには、BootstrapをSass(SCSS)として組み込む必要があります。その際、ユーティリティAPIを使用して独自のユーティリティクラスを作成できます。

ただ、あなたが提示してくれたコードを見ると、Bootstrapのオパシティを設定しているように見えます。しかし、あなたが望んでいるのは、位置を設定することだと理解しています。そのため、以下のように設定する必要があるかもしれません。

```SCSS
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";

$utilities: (
  "position": (
    "top": (
      values: ( 10: 10%, 20: 20%, 30: 30%, 40: 40%, 60: 60%, 70: 70%, 80: 80%, 90: 90% ),
      responsive: true,
      property: "top"
    ),
    "start": (
      values: ( 10: 10%, 20: 20%, 30: 30%, 40: 40%, 60: 60%, 70: 70%, 80: 80%, 90: 90% ),
      responsive: true,
      property: "left"
    ),
  )
);

@import "bootstrap/scss/utilities/api";
```

ここで、値はパーセンテージを使用し、そのために各数値の後に%を追加しています。

また、上記のコードはBootstrapのSassの基本的なファイルをインポートしています。これらがないと、ユーティリティAPIは機能しないので注意してください。

ただし、Bootstrapのバージョンや設定によっては、必要なファイルのインポートや設定が異なる場合があります。具体的な問題の解決には、プロジェクトの全体的な設定や環境を把握することが重要です。

なお、Bootstrapの設定を調整した後は、SCSSをコンパイルして更新されたCSSを適用する必要があります。そのためには、Sassを用いてSCSSファイルをCSSにコンパイルし、その結果をHTMLで利用できるように設定する必要があります。

以上が基本的な解決方法ですが、具体的な問題解決のためには、もう少し詳しい情報（例えばBootstrapのセットアップ方法、Railsのバージョンや設定など）が必要となることをご理解ください。
